"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class position_t(object):
    """ Position broadcasted by nodes """

    __slots__ = ["name", "active", "x", "y"]

    __typenames__ = ["string", "boolean", "int64_t", "int64_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.name = ""
        """ LCM Type: string """
        self.active = False
        """ LCM Type: boolean """
        self.x = 0
        """ LCM Type: int64_t """
        self.y = 0
        """ LCM Type: int64_t """

    def encode(self):
        buf = BytesIO()
        buf.write(position_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">bqq", self.active, self.x, self.y))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != position_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return position_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = position_t()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.active = bool(struct.unpack('b', buf.read(1))[0])
        self.x, self.y = struct.unpack(">qq", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if position_t in parents: return 0
        tmphash = (0x630299995db596a2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if position_t._packed_fingerprint is None:
            position_t._packed_fingerprint = struct.pack(">Q", position_t._get_hash_recursive([]))
        return position_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", position_t._get_packed_fingerprint())[0]

